languageCode = "zh_cn"
title = "诗与胡说"
baseURL = "https://kylingit.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "kylinking"
disqusshortname = "kylingit"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 02, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "一个孤独散步者的梦"
copyright = "Copyright © 2017 kylinking"
logofile = "img/logo.png"
faviconfile = "img/favicon.png"
highlightjs = true
progressively = true
lang = "zh"
github = "kylingit"
email = "ikylinking@gmail.com"
linkedin = ""
twitter = ""

